import fs from "fs";
import path from "path";

const DB_PATH = path.join(process.cwd(), "gxpilot.json");

export interface AuditTrailEvent {
  time: string;
  user: string;
  event: string;
}

export interface Document {
  id: string;
  name: string;
  type: string; // 'SOP', 'APQR', 'MBR', 'EBR', 'General'
  status: string; // 'Draft', 'Under_Review', 'Approved', 'Rejected'
  content: string;
  content_type: string;
  file_size: number;
  audit_trail: AuditTrailEvent[];
  created_at: string;
  updated_at: string;
}

export interface Anomaly {
  type: string;
  severity: "High" | "Medium" | "Low";
  message: string;
}

export interface ChecklistItem {
  item: string;
  status: "PASS" | "FAIL" | "N/A";
}

export interface ComplianceCheck {
  id: string;
  document_id: string;
  score: number;
  status: "Approved" | "Flagged" | "Rejected";
  anomalies: Anomaly[];
  recommendations: string[];
  checklist: ChecklistItem[];
  created_at: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

export interface RoiMetric {
  id: string;
  task_type: string;
  hours_saved: number;
  errors_prevented: number;
  cost_saved_usd: number;
  created_at: string;
}

interface DatabaseSchema {
  documents: Document[];
  compliance_checks: ComplianceCheck[];
  chat_history: ChatMessage[];
  roi_metrics: RoiMetric[];
}

let db: DatabaseSchema = {
  documents: [],
  compliance_checks: [],
  chat_history: [],
  roi_metrics: []
};

// Seed initial data
function getInitialData(): DatabaseSchema {
  const nowStr = new Date().toISOString();
  return {
    documents: [
      {
        id: "doc-1",
        name: "SOP-QA-001_v1.0_Standard_Operating_Procedure_for_Batch_Release.txt",
        type: "SOP",
        status: "Approved",
        content: "This document details the standard operating procedure for reviewing and releasing finished pharmaceutical batches. All critical process parameters (CPPs) must be validated by double QA signatures.",
        content_type: "text/plain",
        file_size: 178,
        audit_trail: [{ time: nowStr, user: "System", event: "Initial SOP Imported (21 CFR 211 compliant)" }],
        created_at: nowStr,
        updated_at: nowStr
      },
      {
        id: "doc-2",
        name: "APQR_Acetaminophen_2025_Draft.txt",
        type: "APQR",
        status: "Under_Review",
        content: "Annual Product Quality Review (APQR) for Acetaminophen 500mg Tablets. Reporting period: Jan 2025 - Dec 2025. Total batches manufactured: 120. Deviations logged: 4 (2 production, 2 packaging). Out of specification (OOS) results: 1 (retested and resolved). Stability trends remain within normal limits (assay 98.5% - 101.2%).",
        content_type: "text/plain",
        file_size: 320,
        audit_trail: [{ time: nowStr, user: "System", event: "APQR Report Draft Generated by GxPilot" }],
        created_at: nowStr,
        updated_at: nowStr
      }
    ],
    compliance_checks: [
      {
        id: "chk-1",
        document_id: "doc-2",
        score: 88.5,
        status: "Flagged",
        anomalies: [
          { type: "Deviation Warning", severity: "Medium", message: "4 deviations logged. Ensure all deviation investigations are signed off in the QMS." },
          { type: "OOS Warning", severity: "High", message: "1 OOS result noted. Retest verification documents must be appended to the final report." }
        ],
        recommendations: [
          "Verify Acetaminophen Batch #ACT25042 retest documentation",
          "Add section 4.3 for Packaging Materials change control",
          "Request QA signoff for deviation DEV-2025-089"
        ],
        checklist: [
          { item: "Executive Summary included", status: "PASS" },
          { item: "Yield trend analysis completed", status: "PASS" },
          { item: "Stability data updated", status: "PASS" },
          { item: "OOS/OOT investigations summarized", status: "FAIL" },
          { item: "Change controls and deviations referenced", status: "PASS" }
        ],
        created_at: nowStr
      }
    ],
    chat_history: [],
    roi_metrics: [
      { id: "roi-1", task_type: "SOP_Prep", hours_saved: 14.5, errors_prevented: 3, cost_saved_usd: 725.0, created_at: "2026-06-25T10:00:00.000Z" },
      { id: "roi-2", task_type: "APQR_Gen", hours_saved: 38.0, errors_prevented: 8, cost_saved_usd: 1900.0, created_at: "2026-06-26T14:30:00.000Z" },
      { id: "roi-3", task_type: "Batch_Review", hours_saved: 24.0, errors_prevented: 5, cost_saved_usd: 1200.0, created_at: "2026-06-28T09:15:00.000Z" },
      { id: "roi-4", task_type: "General_Review", hours_saved: 12.0, errors_prevented: 2, cost_saved_usd: 600.0, created_at: "2026-06-29T16:45:00.000Z" }
    ]
  };
}

export function initDb() {
  try {
    if (fs.existsSync(DB_PATH)) {
      const data = fs.readFileSync(DB_PATH, "utf-8");
      db = JSON.parse(data);
    } else {
      db = getInitialData();
      saveDb();
    }
    console.log("[Node DB] Database initialized successfully.");
  } catch (error) {
    console.error("[Node DB] Error initializing database:", error);
    db = getInitialData();
  }
}

export function saveDb() {
  try {
    fs.writeFileSync(DB_PATH, JSON.stringify(db, null, 2), "utf-8");
  } catch (error) {
    console.error("[Node DB] Error saving database:", error);
  }
}

export function getDocuments(type?: string): Document[] {
  if (type) {
    return db.documents.filter(doc => doc.type === type);
  }
  return db.documents;
}

export function getDocument(id: string): Document | undefined {
  return db.documents.find(doc => doc.id === id);
}

export function getComplianceCheck(documentId: string): ComplianceCheck | undefined {
  return db.compliance_checks.find(chk => chk.document_id === documentId);
}

export function insertDocument(doc: Document) {
  db.documents.unshift(doc);
  saveDb();
}

export function insertComplianceCheck(chk: ComplianceCheck) {
  db.compliance_checks.unshift(chk);
  saveDb();
}

export function addAuditTrailEvent(docId: string, event_text: string, user: string = "GxPilot AI") {
  const doc = getDocument(docId);
  if (doc) {
    if (!doc.audit_trail) doc.audit_trail = [];
    doc.audit_trail.push({
      time: new Date().toISOString(),
      user,
      event: event_text
    });
    doc.updated_at = new Date().toISOString();
    saveDb();
  }
}

export function updateDocumentStatus(docId: string, status: string, reviewerName: string) {
  const doc = getDocument(docId);
  if (doc) {
    doc.status = status;
    doc.updated_at = new Date().toISOString();
    addAuditTrailEvent(docId, `Document status changed to ${status} via physical signoff by ${reviewerName} (21 CFR Part 11 compliant digital signature)`, reviewerName);
    saveDb();
  }
}

export function deleteDocumentAndReviews(docId: string) {
  db.documents = db.documents.filter(doc => doc.id !== docId);
  db.compliance_checks = db.compliance_checks.filter(chk => chk.document_id !== docId);
  saveDb();
}

export function getChatHistory(): ChatMessage[] {
  return db.chat_history;
}

export function insertChatMessage(role: "user" | "assistant", content: string) {
  const msg: ChatMessage = {
    id: `msg-${Math.random().toString(36).substr(2, 9)}`,
    role,
    content,
    timestamp: new Date().toISOString()
  };
  db.chat_history.push(msg);
  saveDb();
  return msg;
}

export function clearChatHistory() {
  db.chat_history = [];
  saveDb();
}

export function getRoiSummary() {
  const total_hours = db.roi_metrics.reduce((acc, curr) => acc + curr.hours_saved, 0);
  const total_errors = db.roi_metrics.reduce((acc, curr) => acc + curr.errors_prevented, 0);
  const total_usd = db.roi_metrics.reduce((acc, curr) => acc + curr.cost_saved_usd, 0);
  
  return {
    summary: {
      total_hours_saved: total_hours,
      total_errors_prevented: total_errors,
      total_cost_saved_usd: total_usd,
      total_tasks_assisted: db.roi_metrics.length,
      hourly_rate_assumption: 50.0
    },
    history: db.roi_metrics
  };
}

export function insertRoiMetric(task_type: string, hours_saved: number, errors_prevented: number, cost_saved_usd: number) {
  const metric: RoiMetric = {
    id: `roi-${Math.random().toString(36).substr(2, 9)}`,
    task_type,
    hours_saved,
    errors_prevented,
    cost_saved_usd,
    created_at: new Date().toISOString()
  };
  db.roi_metrics.unshift(metric);
  saveDb();
  return metric;
}
